### ISSUE TITLE
Reference to inexistent ftr.obo file

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#2144]
The `make-bridge-ontologies-from-xrefs.pl` script tries to open a file named `ftr.obo`:

```perl
open(F,"ftr.obo");
while(<F>) {
    print $fh $_;
}
close(F);
```

This file does not exist and is not referenced anywhere else in the repository (there’s no rule to generate it).

Does anyone know what is, or rather _was_, the purpose of this file? Should that file exist?

The above code causes a bunch of Perl warnings when generating the bridge files, because it tries to read from the file handle even when the handle is not valid due to the file not being present.

**Comment by gouttegd** [comment]
I suspect `ftr` might stand for _footer_, and that the point of the above snippet is to allow to include an arbitrary piece of OBO code at the end of all the generated bridge files, simply by putting the piece into a `ftr.obo` file.

We’re not using that feature right now but it could become handy in the future, so I think the proper thing to do here is to keep the snippet, but with proper handling of the condition where the `ftr.obo` is absent to avoid cluttering the output with warnings.

**Comment by cmungall** [comment]
```yaml
[Typedef]
id: foaf-depicted_by
name: depicted_by
is_metadata_tag: true
xref: http://xmlns.com/foaf/0.1/depicted_by

[Typedef]
id: foaf-homepage
name: homepage
is_metadata_tag: true
xref: http://xmlns.com/foaf/0.1/homepage

[Typedef]
id: dc-title
name: title
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/title

[Typedef]
id: dc-contributor
name: contributor
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/contributor

[Typedef]
id: dc-creator
name: creator
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/creator

[Typedef]
id: dc-publisher
name: publisher
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/publisher

[Typedef]
id: dc-description
name: description
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/description

[Typedef]
id: dc-source
name: derived from resource
is_metadata_tag: true
xref: http://purl.org/dc/elements/1.1/source

[Typedef]
id: dcterms-isReferencedBy
name: is referenced by
is_metadata_tag: true
xref: http://purl.org/dc/terms/isReferencedBy

[Typedef]
id: dcterms-references
name: references
is_metadata_tag: true
xref: http://purl.org/dc/terms/references

[Typedef]
id: doap-GitRepository
name: Git repository
is_metadata_tag: true
xref: http://usefulinc.com/ns/doap#GitRepository

[Typedef]
id: doap-SVNRepository
name: SVN repository
is_metadata_tag: true
xref: http://usefulinc.com/ns/doap#SVNRepository

[Typedef]
id: doap-wiki
name: wiki
is_metadata_tag: true
xref: http://usefulinc.com/ns/doap#wiki

[Typedef]
id: doap-bug-database
name: bug database
is_metadata_tag: true
xref: http://usefulinc.com/ns/doap#bug-database

[Typedef]
id: seeAlso
name: see also
is_metadata_tag: true
xref: http://www.w3.org/2000/01/rdf-schema#seeAlso

[Typedef]
id: example_of_usage
name: example of usage
is_metadata_tag: true
xref: IAO:0000122
```
