### ISSUE TITLE
Add design pattern for mixed layers (specifically cortical)

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2149]
I am looking at @shawntanzk's PR #2089  - great work!

This introduces new terms like neocortex layer 2/3

However, these are not related to existing terms like neocortex layer 2 and layer 3

```yaml
[Term]
id: UBERON:8440000
name: cortical layer II/III
def: "A laminar subdivision of the neocortex that is comprised of both layers II & III." [PMID:34616063]
synonym: "cerebral cortex layer 2/3" EXACT []
synonym: "neocortex layer 2/3" EXACT []
is_a: UBERON:8440004 ! laminar subdivision of the cortex
```

The definition reads like a mereological sum rather than a class union. Unfortunately these are harder to reason with in OWL (we can do a GCI disjoint union and then materialize), but we can assert for now

The SOP should be if you add a new term A+B then add axioms {A,B} subClassOf part-of some A+B

(ultimately we'd like all the adjacency relations but this can wait)

An annoying wrinkle here might be if one taxon lacks a layer and thus a combined layer, we'd have to add a taxon CGI which is getting really complex. So I think it's also good to cuation against adding species-variable mereological sums.
