### ISSUE TITLE
incorrect axiom: endochrondral bone develops-from sublingual cartilage 

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2159]
![image](https://user-images.githubusercontent.com/50745/141005865-88eb924f-e50d-4431-84a7-1977c5774f02.png)

```yaml
id: UBERON:0002513
name: endochondral bone
def: "Replacement bone that forms within cartilage." [GO:0001958, GO_REF:0000034, http://dx.plos.org/10.1371/journal.pone.0051070, https://github.com/obophenotype/uberon/issues/54, VSAO:0000145]
subset: uberon_slim
subset: vertebrate_core
synonym: "cartilaginous bone" RELATED [BTO:0002157]
synonym: "endochondral bones" RELATED PLURAL [ZFA:0001591]
synonym: "ossified chondrogenic bone" EXACT [VSAO:0000145]
xref: AAO:0010776
xref: AEO:0000083
xref: BTO:0002157
xref: EHDAA2:0003083
xref: FMA:24321
xref: TAO:0001591
xref: VSAO:0000145
xref: XAO:0004018
xref: ZFA:0001591
is_a: UBERON:0010363 {source="VSAO"} ! endochondral element
intersection_of: UBERON:0001474 ! bone element
intersection_of: develops_from UBERON:0005863 ! cartilaginous condensation
relationship: developmentally_replaces UBERON:0002418 ! cartilage tissue
relationship: develops_from UBERON:0007844 {source="VSAO"} ! cartilage element
******relationship: develops_from UBERON:2001544 ! sublingual cartilage
```

@balhoff I think this is yours :-) 9b6e48576b
