### ISSUE TITLE
Review all anatomical lines

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2215]
Extending #2214 

I think many lines in uberon are not lines, causing cryptic incoherencies

Here is one strategy

First create explicit DPs for all line and boundary patterns

## line connecting patterns

 1. anatomical line connecting two distinct structures: `line connecting % to %`
 2. anatomical line connecting two paralogous structures of the same type (must use QCR, outside EL++). `inter-% line`

these are true abstract lines and should never have cells, genes, etc in them

ANY class with `line` at end of label MUST conform to one of these

Example of violation:

```
id: UBERON:2007027
name: forebrain midbrain boundary neural keel
xref: ZFA:0007027
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:0009612 ! forebrain midbrain boundary neural plate
relationship: part_of UBERON:2007024 ! anterior neural keel
```

## boundary patterns

these should be material

 1. X-Y boundary
 2. boundary, lacking clear logical def

IF a term has boundary in its label, it MUST conform to this

example of violation

```yaml
id: UBERON:2001343
name: telencephalon diencephalon boundary
xref: ZFA:0001343
is_a: UBERON:0006800 ! anatomical line
relationship: part_of UBERON:0001890 ! forebrain
```

## unsure what to do with

```yaml```

**Comment by megbalk** [comment]
@cmungall are we going to discuss this at the next meeting? Maybe we could discuss midlines too?

**Comment by shawntanzk** [comment]
Look at uberon 2x terms that are under anatomical line and see which are actually lines and which arent

**Comment by cmungall** [comment]
```yaml

[Term]
id: UBERON:0000464 ! anatomical space
name: anatomical space
is_a: UBERON:0000466 ! immaterial anatomical entity
relationship: surrounded_by UBERON:0000061 ! anatomical structure

[Term]
id: UBERON:0002225 ! costal arch
name: costal arch
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: part_of UBERON:0001443 ! chest
relationship: part_of UBERON:0002228 {source="MA"} ! rib

[Term]
id: UBERON:0004104 ! hairline
name: hairline
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0000403 ! scalp
intersection_of: connects UBERON:0008200 ! forehead
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens
relationship: part_of UBERON:0000033 ! head

[Term]
id: UBERON:0006800 ! anatomical line
name: anatomical line
is_a: UBERON:0000015 ! non-material anatomical boundary

[Term]
id: UBERON:0009038 ! sulcus ampullaris
name: sulcus ampullaris
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: contributes_to_morphology_of UBERON:0001846 ! internal ear
relationship: part_of UBERON:0004043 {source="MA"} ! semicircular canal ampulla

[Term]
id: UBERON:0009612 ! forebrain midbrain boundary neural plate
name: forebrain midbrain boundary neural plate
is_a: UBERON:0006800 {source="ZFA"} ! anatomical line
relationship: develops_from UBERON:0007288 {source="ZFA"} ! presumptive forebrain midbrain boundary
relationship: part_of UBERON:0003056 {source="ZFA"} ! pre-chordal neural plate

[Term]
id: UBERON:0009848 ! zona limitans intrathalamica
name: zona limitans intrathalamica
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: adjacent_to UBERON:0001900 ! ventral thalamus
intersection_of: adjacent_to UBERON:0004703 ! dorsal thalamus
relationship: part_of UBERON:0001897 {source="ZFA"} ! dorsal plus ventral thalamus

[Term]
id: UBERON:0010222 ! anatomical line between pupils
name: anatomical line between pupils
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0010223 ! left pupil
intersection_of: connects UBERON:0010224 ! right pupil
relationship: part_of UBERON:0001456 ! face

[Term]
id: UBERON:0010231 ! anatomical line between outer ears
name: anatomical line between outer ears
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0006616 ! right external ear
intersection_of: connects UBERON:0006617 ! left external ear

[Term]
id: UBERON:0011877 ! margin of tongue
name: margin of tongue
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0007371 ! superior surface of tongue
intersection_of: connects UBERON:0007373 ! inferior surface of tongue
relationship: part_of UBERON:0001723 ! tongue

[Term]
id: UBERON:0011918 ! line of Schwalbe
name: line of Schwalbe
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: contributes_to_morphology_of UBERON:0005969 ! eye trabecular meshwork
relationship: part_of UBERON:0000964 ! cornea
relationship: part_of UBERON:0005969 {source="MP"} ! eye trabecular meshwork

[Term]
id: UBERON:0012079 ! metapterygial axis
name: metapterygial axis
is_a: UBERON:0006800 ! anatomical line
relationship: only_in_taxon NCBITaxon:7742 ! Vertebrata <vertebrates>
relationship: part_of UBERON:0000026 ! appendage

[Term]
id: UBERON:0012437 ! epithelial-mesenchymal boundary
name: epithelial-mesenchymal boundary
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: adjacent_to UBERON:0000483 ! epithelium
intersection_of: adjacent_to UBERON:0003104 ! mesenchyme
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa

[Term]
id: UBERON:0013445 ! pterygomaxillary fissure
name: pterygomaxillary fissure
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: part_of UBERON:0003129 {source="Wikipedia"} ! skull

[Term]
id: UBERON:0013455 ! spheno-petrosal fissure
name: spheno-petrosal fissure
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0001677 ! sphenoid bone
intersection_of: connects UBERON:0001694 ! petrous part of temporal bone
relationship: part_of UBERON:0003129 {source="Wikipedia"} ! skull

[Term]
id: UBERON:0013633 ! intertrochanteric crest
name: intertrochanteric crest
is_a: UBERON:0006800 ! anatomical line
relationship: connects UBERON:0002503 ! greater trochanter
relationship: connects UBERON:0002504 ! lesser trochanter
relationship: part_of UBERON:0004412 ! proximal epiphysis of femur

[Term]
id: UBERON:0013634 ! intertrochanteric line
name: intertrochanteric line
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: part_of UBERON:0004412 ! proximal epiphysis of femur

[Term]
id: UBERON:0013670 ! midline of corpus cavernosum maxillaris
name: midline of corpus cavernosum maxillaris
is_a: UBERON:0006800 ! anatomical line
relationship: part_of UBERON:0013658 ! corpus cavernosum maxillaris

[Term]
id: UBERON:0013678 ! anatomical line between inner canthi
name: anatomical line between inner canthi
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0013679 ! inner canthus of right eye
intersection_of: connects UBERON:0013680 ! inner canthus of left eye
intersection_of: part_of UBERON:0001456 ! face

[Term]
id: UBERON:0013692 ! inframammary fold
name: inframammary fold
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: adjacent_to UBERON:0000310 ! breast
relationship: adjacent_to UBERON:0001443 ! chest
relationship: part_of UBERON:0002100 ! trunk

[Term]
id: UBERON:0013770 ! intermammary cleft
name: intermammary cleft
is_a: UBERON:0006800 {source="FMA"} ! anatomical line
relationship: only_in_taxon NCBITaxon:40674 ! Mammalia
relationship: part_of UBERON:0002100 ! trunk

[Term]
id: UBERON:0013771 ! line connecting laterally paired nipples
name: line connecting laterally paired nipples
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0013772 ! left nipple
intersection_of: connects UBERON:0013773 ! right nipple
intersection_of: has_quality PATO:0001854 ! vertical
relationship: part_of UBERON:0002100 ! trunk

[Term]
id: UBERON:0014764 ! anatomical line along groove
name: anatomical line along groove
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: in_superficial_part_of UBERON:0006846 ! surface groove

[Term]
id: UBERON:0015122 ! anatomical line between outer canthi
name: anatomical line between outer canthi
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0015120 ! right outer canthus
intersection_of: connects UBERON:0015121 ! left outer canthus
intersection_of: part_of UBERON:0001456 ! face

[Term]
id: UBERON:0015854 ! interpedicular line
name: interpedicular line
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0001078 {cardinality="2"} ! pedicle of vertebra
relationship: connects UBERON:0001078 ! pedicle of vertebra
relationship: part_of UBERON:0001130 ! vertebral column

[Term]
id: UBERON:0036013 ! intergluteal cleft
name: intergluteal cleft
intersection_of: UBERON:0006800 {exactly="2"} ! anatomical line
intersection_of: adjacent_to UBERON:0013691 {exactly="2"} ! buttock
relationship: adjacent_to UBERON:0013691 ! buttock
relationship: part_of UBERON:0001137 ! dorsum
relationship: part_of UBERON:0002355 ! pelvic region of trunk

[Term]
id: UBERON:2001343 ! telencephalon diencephalon boundary
name: telencephalon diencephalon boundary
is_a: UBERON:0006800 ! anatomical line
relationship: part_of UBERON:0001890 ! forebrain

[Term]
id: UBERON:2002051 ! scale circulus
name: scale circulus
is_a: UBERON:0006800 ! anatomical line
relationship: part_of UBERON:0007380 ! dermal scale

[Term]
id: UBERON:2007027 ! forebrain midbrain boundary neural keel
name: forebrain midbrain boundary neural keel
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:0009612 ! forebrain midbrain boundary neural plate
relationship: part_of UBERON:2007024 ! anterior neural keel

[Term]
id: UBERON:2007033 ! forebrain midbrain boundary neural rod
name: forebrain midbrain boundary neural rod
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:2007027 ! forebrain midbrain boundary neural keel
relationship: part_of UBERON:2007031 ! anterior neural rod

[Term]
id: UBERON:2007040 ! forebrain midbrain boundary neural tube
name: forebrain midbrain boundary neural tube
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:2007033 ! forebrain midbrain boundary neural rod
relationship: part_of UBERON:0003080 ! anterior neural tube

[Term]
id: UBERON:2007045 ! midbrain hindbrain boundary neural keel
name: midbrain hindbrain boundary neural keel
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:0009615 ! midbrain hindbrain boundary neural plate
relationship: part_of UBERON:0007135 ! neural keel

[Term]
id: UBERON:2007046 ! midbrain hindbrain boundary neural rod
name: midbrain hindbrain boundary neural rod
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:2007045 ! midbrain hindbrain boundary neural keel
relationship: part_of UBERON:0005068 ! neural rod

[Term]
id: UBERON:2007047 ! midbrain hindbrain boundary neural tube
name: midbrain hindbrain boundary neural tube
is_a: UBERON:0006800 ! anatomical line
relationship: develops_from UBERON:2007046 ! midbrain hindbrain boundary neural rod
relationship: part_of UBERON:0001049 ! neural tube

[Term]
id: UBERON:4200221 ! growth line
name: growth line
is_a: UBERON:0006800 ! anatomical line

[Term]
id: UBERON:7500036 ! line from caundal-sacral region of the vertebral column to the last vertebra
name: line from caundal-sacral region of the vertebral column to the last vertebra
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0011271 ! caudal-sacral region of vertebral column
intersection_of: connects UBERON:7500035 ! tip of tail

[Term]
id: UBERON:7500037 ! line from helix of outer ear to intertragus incisure
name: line from helix of outer ear to intertragus incisure
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0002488 ! helix of outer ear
intersection_of: connects UBERON:0036212 ! intertragic incisure

[Term]
id: UBERON:7500038 ! line from the distal-most end of the longest nail to the posterior-most part of the foot
name: line from the distal-most end of the longest nail to the posterior-most part of the foot
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:7500039 ! posterior of pes
intersection_of: connects UBERON:7500040 ! tip of nail

[Term]
id: UBERON:7500042 ! line from the distal-most end of the longest phalax of the foot to the posterior-most part of the foot
name: line from the distal-most end of the longest phalax of the foot to the posterior-most part of the foot
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0009551 ! distal segment of digit
intersection_of: connects UBERON:7500039 ! posterior of pes

[Term]
id: UBERON:7500043 ! line from tip of nose to the caudal-sacral region of the vertebral column
name: line from tip of nose to the caudal-sacral region of the vertebral column
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0011271 ! caudal-sacral region of vertebral column
intersection_of: connects UBERON:0012128 ! nose tip

[Term]
id: UBERON:7500044 ! line from tip of nose to the posterior-most part of the last caudal vertebra
name: line from tip of nose to the posterior-most part of the last caudal vertebra
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:0012128 ! nose tip
intersection_of: connects UBERON:7500035 ! tip of tail

[Term]
id: UBERON:7500045 ! line of medial condyle of femur to greater trochanter
name: line of medial condyle of femur to greater trochanter
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:7500033 ! distal-most point of medial condyle of femur
intersection_of: connects UBERON:7500049 ! proximal-most point of greater trochanter of femur

[Term]
id: UBERON:7500050 ! line of medial condyle of femur to head of femur
name: line of medial condyle of femur to head of femur
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:7500033 ! distal-most point of medial condyle of femur
intersection_of: connects UBERON:7500046 ! proximal-most point of head of femur

[Term]
id: UBERON:7500051 ! line from trochlea of humerus to proximal head of humerus
name: line from trochlea of humerus to proximal head of humerus
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:7500034 ! distal-most point of trochlea of humerus
intersection_of: connects UBERON:7500047 ! proximal-most point of head of humerus

[Term]
id: UBERON:7500060 ! line from trochlea of humerus to ventral tubercle of humerus
name: line from trochlea of humerus to ventral tubercle of humerus
intersection_of: UBERON:0006800 ! anatomical line
intersection_of: connects UBERON:7500034 ! distal-most point of trochlea of humerus
intersection_of: connects UBERON:7500048 ! proximal-most point of ventral tubercle of humerus

```
