### ISSUE TITLE
Figure out how to increase memory for GitHub actions

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2337]
see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners (mac-os image or something like that)

**Comment by shawntanzk** [comment]
related to https://github.com/pato-ontology/pato/blob/master/.github/workflows/imports.yaml

**Comment by shawntanzk** [comment]
https://github.com/obophenotype/uberon/pull/2408/files

**Comment by ubyndr** [comment]
```
    runs-on: macos-latest
    # container: obolibrary/odkfull:latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
      - name: Install ODK
        run: docker pull obolibrary/odklite
```
We are using MacOs runner, and install docker and ODK image manually.
