### ISSUE TITLE
gonad is inappropriately placed in the renal system

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2514]
From @balhoff in GO:

![image](https://user-images.githubusercontent.com/50745/171673900-f135c23a-0926-42a4-bfff-9f0e2bc5d59e.png)

the fact this wasn't caught in the uberon release system is a problem in itself

Another tip: be very very conservative with uberon IDs in the 2x, 3x and 4x range. This term “genital system” is from AAO. It should probably be merged. In the interim, be ultra-careful when linking classes to these terms

```yaml
id: UBERON:3011048
name: genital system
def: "Anatomical system that has as its parts the organs concerned with reproduction, especially the external genital organs." [https://www.merriam-webster.com/dictionary/genitalia, XAO:0000142]
synonym: "genitalia" BROAD []
synonym: "reproductive system" BROAD []
is_a: UBERON:0000467 ! anatomical system
relationship: part_of UBERON:0004122 ! genitourinary system
property_value: provenance_notes "This class was sourced from an external ontology (amphibian_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon" xsd:string {source="http://purl.obolibrary.org/obo/aao.owl"}
```
