### ISSUE TITLE
Nerves and branches of nerves should be subclass of nerve not tissue

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/uberon#2517]
The explanation makes it easy to see what's going wrong:

```yaml
id: UBERON:3010726
name: ramus muscularis of glossopharyngeus nerve
def: "Branchiomotor branch of the glossopharyngeus nerve innervating the m. subarcuales rectus I." [AAO:EJS]
is_a: UBERON:0000479 ! tissue
relationship: innervates UBERON:3010659 ! subarcualis rectus I
relationship: part_of UBERON:0001649 ! glossopharyngeal nerve
property_value: provenance_notes "This class was sourced from an external ontology (amphibian_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon" xsd:string {source="http://purl.obolibrary.org/obo/aao.owl"}
```

in uberon, both nerves and branches of nerves should be subclass of nerve not tissue

_Originally posted by @cmungall in https://github.com/obophenotype/uberon/issues/2495#issuecomment-1143851635_
