### ISSUE TITLE
Obsolete `aggregate regional part of brain`

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/uberon#2627]
on reflection, this is a poor grouping class:

```yaml
id: UBERON:0010009
name: aggregate regional part of brain
def: "A regional part of brain consisting of multiple brain regions that are not related through a simple volummetric part of hierarchy, e.g., basal ganglia[NIF]." [NLXANAT:20090509]
subset: non_informative
synonym: "set of nuclei of neuraxis" RELATED [FMA:256381]
xref: FMA:256381
xref: NLXANAT:20090509
intersection_of: UBERON:0034923 ! disconnected anatomical group
intersection_of: has_member UBERON:0002616 ! regional part of brain
intersection_of: part_of UBERON:0000955 ! brain
property_value: editor_note "May be obsoleted." xsd:string
```

The over-eager logical definition does not match the textual definition, I am not even sure I understand the textual definition

As a grouping class it doesn't do much work, grouping only 3 regions:

* [] BFO:0000001 ! entity
    * [i] BFO:0000002 ! continuant
        * [i] BFO:0000004 ! independent continuant
            * [i] CARO:0030000 ! biological entity
                * [i] CARO:0000000 ! anatomical entity
                    * [i] **UBERON:0010009 ! aggregate regional part of brain**
                        * [i] UBERON:0014370 ! extrastriate cortex
                        * [i] UBERON:0010011 ! collection of basal ganglia
                            * [i] UBERON:0023920 ! basal ganglia of rodent
                        * [i] UBERON:0000431 ! ventral medial complex of thalamus

If there really is something distinct about these then this should be asserted using something like pato characteristics (and it should be done consistently with reasonable completeness)

- Conservative solution: replace the logical definition with `is_a regional part of brain`
- My preferred solution: obsolete the grouping and rewire the above terms to RPoB

_Originally posted by @cmungall in https://github.com/obophenotype/uberon/issues/2495#issuecomment-1208532662_
