### ISSUE TITLE
Avoid logical definitions with two part-ofs as differentia

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2696]
this is an antipattern:

```yaml
id: UBERON:0017612
name: cingulum of lower jaw molar
def: "A ridge that girdles the base of a lower molar tooth." [http://en.wiktionary.org/wiki/cingulid]
synonym: "cingulid" BROAD []
synonym: "cingulid of molar tooth" EXACT []
synonym: "tooth cingulid" RELATED []
intersection_of: UBERON:0017295 ! cingulum of tooth
intersection_of: part_of UBERON:0001710 ! lower jaw region
intersection_of: part_of UBERON:0003655 ! molar tooth
```

Rationale: we have a precoordinated term "lower jaw molar", and this DP and OWL reasoning is insufficient to infer the crucial part-of between these two.

Formally this is the *co-reference* problem, so I would classify as a *co-reference antipattern*. Even if we use a method like materialize or RG to materialize A sub R some B, formally we have models in which the MT is not part of the LJR
