### ISSUE TITLE
Document design patterns for named nerves

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#298]
The representation of nerves and their parts varies wildly from ontology to ontology. We should create a shared set of design patterns for nerves.

This item serves as a draft for this design pattern. The text here will be altered on the basis of comments entered below.

Anyone is welcome to comment. Particularly interested in comments on nerve innervation from David OS and @RDruzinsky 

the focus of this articles is vertebrates, but much can be learned from work done on invertebrates. See in particular the representation of neuron connectivity in VFB and FlyBase:

A strategy for building neuroanatomy ontologies
D Osumi-Sutherland, S Reeve, CJ Mungall, F Neuhaus… - Bioinformatics, 2012
http://bioinformatics.oxfordjournals.org/content/28/9/1262.short
## Nerve categorization

A fairly standard subdivision into cranial and spinal:
- [UBERON:0005162](http://purl.obolibrary.org/obo/UBERON_0005162) ! multi cell component structure
  - [UBERON:0000122](http://purl.obolibrary.org/obo/UBERON_0000122) ! neuron projection bundle
    - [UBERON:0001021](http://purl.obolibrary.org/obo/UBERON_0001021) ! nerve
      - [UBERON:0001780](http://purl.obolibrary.org/obo/UBERON_0001780) ! spinal nerve  
      - [UBERON:0001785](http://purl.obolibrary.org/obo/UBERON_0001785) ! cranial nerve  

Note however, that not every CN is a true PNS nerve. More on this later.
## Nerve subdivisions

Nerves can be subdivided
1. _lengthwise_ from their origin in the CNS to their destination. e.g a muscle
2. in cross-section - e.g. into bundles of axons, epineurium etc

We focus here on 1 as this is where some inconsistencies currently lie. However, our answers to 1 depend to a large extent on 2, as nerves must be defined in terms of cellular components such as axons.

The open question here is roots - are roots considered part of the nerve, part of the CNS (ie brain for CNs), or do they overap? We have to be careful as if the CNS and PNS are considered not to overlap, and nerves are considered entirely part of the PNS we get incoherent ontologies quickly.

We must also consider _axon tracts_ here. E.g.
- [UBERON:0001018](http://purl.obolibrary.org/obo/UBERON_0001018) ! axon tract  
  - [UBERON:0001020](http://purl.obolibrary.org/obo/UBERON_0001020) ! commissure
  - [UBERON:0002753](http://purl.obolibrary.org/obo/UBERON_0002753) ! posterior spinocerebellar tract
  - [UBERON:0004171](http://purl.obolibrary.org/obo/UBERON_0004171) ! trigeminothalamic tract
  - [UBERON:0004172](http://purl.obolibrary.org/obo/UBERON_0004172) ! pons reticulospinal tract
  - [UBERON:0004173](http://purl.obolibrary.org/obo/UBERON_0004173) ! medulla reticulospinal tract
  - [UBERON:0005821](http://purl.obolibrary.org/obo/UBERON_0005821) ! gracile fasciculus
  - [UBERON:0005832](http://purl.obolibrary.org/obo/UBERON_0005832) ! cuneate fasciculus
  - [UBERON:0007699](http://purl.obolibrary.org/obo/UBERON_0007699) ! tract of spinal cord
  - [UBERON:0007702](http://purl.obolibrary.org/obo/UBERON_0007702) ! tract of brain
  - [UBERON:0011591](http://purl.obolibrary.org/obo/UBERON_0011591) ! tract of diencephalon
### Origin

What is the relationship to the brain structure sending the signal? In spatial terms the answer depends in part on how we handle roots above, and must be guided by relationships at the level of cell components
### Innervation

The RO relation needs generalizing to be applicable to muscles, skin etc

See: http://code.google.com/p/obo-relations/issues/detail?id=6
## Development

Is the relationship between the placodes develops_from or has developmental contribution from?

For cranial nerves (CNs) here is a subset of the current hierarchy
-  [UBERON:0002546](http://purl.obolibrary.org/obo/UBERON_0002546) ! cranial placode
  -  [UBERON:0009955](http://purl.obolibrary.org/obo/UBERON_0009955) ! neurogenic placode  
    -  [UBERON:0003050](http://purl.obolibrary.org/obo/UBERON_0003050) ! olfactory placode
      - df  [UBERON:0000004](http://purl.obolibrary.org/obo/UBERON_0000004) ! olfactory apparatus
      - df  [UBERON:0001579](http://purl.obolibrary.org/obo/UBERON_0001579) ! olfactory nerve
      - df  [UBERON:0001997](http://purl.obolibrary.org/obo/UBERON_0001997) ! olfactory epithelium
      - df  [UBERON:0002255](http://purl.obolibrary.org/obo/UBERON_0002255) ! vomeronasal organ
      - df  [UBERON:0005870](http://purl.obolibrary.org/obo/UBERON_0005870) ! olfactory pit
      - df  [UBERON:0009121](http://purl.obolibrary.org/obo/UBERON_0009121) ! vomeronasal nerve
    -  [UBERON:0003067](http://purl.obolibrary.org/obo/UBERON_0003067) ! dorsolateral placode
      -  [UBERON:0003069](http://purl.obolibrary.org/obo/UBERON_0003069) ! otic placode
      -  [UBERON:0003070](http://purl.obolibrary.org/obo/UBERON_0003070) ! trigeminal placode
      -  [UBERON:0009128](http://purl.obolibrary.org/obo/UBERON_0009128) ! lateral line placode
      -  [UBERON:2001156](http://purl.obolibrary.org/obo/UBERON_2001156) ! posterior lateral line placode
      -  [UBERON:2001316](http://purl.obolibrary.org/obo/UBERON_2001316) ! anterior lateral line placode
      -  [UBERON:2005121](http://purl.obolibrary.org/obo/UBERON_2005121) ! middle lateral line placode
    -  [UBERON:0003078](http://purl.obolibrary.org/obo/UBERON_0003078) ! epibranchial placode
      -  [UBERON:0009124](http://purl.obolibrary.org/obo/UBERON_0009124) ! geniculate placode
      -  [UBERON:0009125](http://purl.obolibrary.org/obo/UBERON_0009125) ! petrosal placode
      -  [UBERON:0009126](http://purl.obolibrary.org/obo/UBERON_0009126) ! nodosal placode
      - df  [UBERON:0009127](http://purl.obolibrary.org/obo/UBERON_0009127) ! epibranchial ganglion
      -  [UBERON:2001297](http://purl.obolibrary.org/obo/UBERON_2001297) ! vagal placode 1
      -  [UBERON:2001298](http://purl.obolibrary.org/obo/UBERON_2001298) ! vagal placode 2
      -  [UBERON:2001299](http://purl.obolibrary.org/obo/UBERON_2001299) ! vagal placode 3
      -  [UBERON:2001300](http://purl.obolibrary.org/obo/UBERON_2001300) ! vagal placode 4
## Branching

Do we consider a nerve a branching structure or a tube-like structure? I.e. is a branch of nerve X also a part of nerve X?

Clue: axons

The answer here should be informed by (but not necessarily identical to) how we treat branching on blood vessels, etc. See #170

Differences in branching may also provide problems for a multi-species representation. CNs are relatively well preserved, but named branches may tend to be lineage specific?
## Optic nerve

Remember this isn't truly a PNS nerve
## Treatment in other ontologies

FMA has an (undefined) "central zone of nerve"

```
        is_a FMA:86142 ! Zone of nerve
         is_a FMA:82524 ! Central zone of nerve *** 
          is_a FMA:72499 ! Vestibulocochlear nerve tract
          is_a FMA:72501 ! Trigeminal nerve tract
          is_a FMA:72627 ! Glossopharyngeal nerve tract
          is_a FMA:72628 ! Vagal nerve tract
```

We assume that "central zone" refers to the zone that is part of the CNS. Thus a nerve - in FMA - is not constrained to be purely PNS (unless we allow CNS and PNS to overlap, which may be an odd decision)

The same hierarchy with parthood relations

```
         is_a FMA:82524 ! Central zone of nerve *** 
          is_a FMA:72499 ! Vestibulocochlear nerve tract [regional_part_of: "Pontine tegmentum"]
          is_a FMA:72501 ! Trigeminal nerve tract [regional_part_of: "Pontine tegmentum"]
          is_a FMA:72627 ! Glossopharyngeal nerve tract [constitutional_part_of: "Medulla oblongata"]
          is_a FMA:72628 ! Vagal nerve tract [constitutional_part_of: "Medulla oblongata"]
```

It's not clear why these are only named for a subset of the cranial nerves.

We can also look at the terminology used:

```
         is_a FMA:82524 ! Central zone of nerve *** 
          is_a FMA:72499 ! Vestibulocochlear nerve tract [SYNONYM: "Central part of vestibulocochlear nerve" (exact)] [SYNONYM: "Statoacoustic nerve fibers" (exact)] [SYNONYM: "Vestibulocochlear nerve fibers" (exact)] [SYNONYM: "Vestibulocochlear nerve roots" (exact)]
          is_a FMA:72501 ! Trigeminal nerve tract [SYNONYM: "Central part of trigeminal nerve" (exact)] [SYNONYM: "Trigeminal nerve fibers" (exact)]
          is_a FMA:72627 ! Glossopharyngeal nerve tract [SYNONYM: "Central part of glossopharyngeal nerve" (exact)] [SYNONYM: "Glossopharyngeal nerve fibers" (exact)] [SYNONYM: "Ninth cranial nerve fibers" (exact)]
          is_a FMA:72628 ! Vagal nerve tract [SYNONYM: "Central part of vagus nerve" (exact)] [SYNONYM: "Tenth cranial nerve fibers" (exact)] [SYNONYM: "Vagal nerve fibers" (exact)]
```

Note that FMA considers "X nerve fibers" "central part of X" and "X tract" as synonyms. Is this correct?

Nerve fibers surely extend into the PNS portion (unless the FMA considers the CNS "tunneling through" the nerves which might be an interesting approach)

Note that NIFSTD creates separate classes for nerve fibers and tracts.

Here are some nerve fibers in NIFSTD:

```
  is_a NIF_GrossAnatomy:birnlex_16 ! Regional part of organ
    is_a NIF_GrossAnatomy:birnlex_1167 ! Regional part of brain
     is_a NIF_GrossAnatomy:birnlex_1172 ! Trochlear nerve fibers *** 
     is_a NIF_GrossAnatomy:birnlex_1274 ! Glossopharyngeal nerve fiber bundle *** 
     is_a NIF_GrossAnatomy:birnlex_1288 ! Hypoglossal nerve fiber bundle *** 
     is_a NIF_GrossAnatomy:birnlex_1323 ! Oculomotor nerve fibers *** 
     is_a NIF_GrossAnatomy:birnlex_1636 ! Vestibulocochlear nerve fiber bundle *** 
     is_a NIF_GrossAnatomy:birnlex_1689 ! Abducens nerve fibers *** 
     is_a NIF_GrossAnatomy:birnlex_765 ! Vagal nerve fiber bundle *** 
     is_a NIF_GrossAnatomy:birnlex_974 ! Trigeminal nerve fibers *** 
    is_a NIF_GrossAnatomy:birnlex_1496 ! Regional part of spinal cord
     is_a NIF_GrossAnatomy:birnlex_916 ! Accessory nerve fiber bundle *** 
```

Note that in NIFSTD the CNS and PNS part-overlap:

```
  is_a NIF_GrossAnatomy:birnlex_6 ! Anatomical entity
   is_a NIF_GrossAnatomy:birnlex_11 ! Regional part of body system
    is_a NIF_GrossAnatomy:birnlex_1157 ! Part of nervous system
     is_a NIF_GrossAnatomy:birnlex_1122 ! Regional part of peripheral nervous system
      is_a NIF_GrossAnatomy:birnlex_1615 ! Nerve part of peripheral nervous system
       is_a NIF_GrossAnatomy:birnlex_1623 ! Cranial nerve
        is_a NIF_GrossAnatomy:birnlex_1319 ! Olfactory nerve
         proper_part_of NIF_GrossAnatomy:birnlex_1632 ! Olfactory nerve root *** 
   is_a NIF_GrossAnatomy:birnlex_16 ! Regional part of organ
    is_a NIF_GrossAnatomy:birnlex_1167 ! Regional part of brain
     is_a NIF_GrossAnatomy:nlx_144250 ! Nerve root
      is_a NIF_GrossAnatomy:birnlex_1632 ! Olfactory nerve root *** 
```

The ON root is part of the brain and part of the PNS

Note the same pattern is not followed for all roots.

**Comment by tgbugs** [comment]
Digging up this issue since it is the cause of many incompatibilities with NIFGA (while these terms are deprecated I want to use them to make sure that when we transition the representations are at least minimally compatible).

At the moment my primary concern is with the optic nerve wrt the cranial nerves. The the simplest way to resolve this issue seems to be to treat 'cranial nerves' as a more colloquial term that includes the optic nerve and the 'peripheral cranial nerves.' This would allow us to treat the optic nerve separately without having to accommodate a definition of nerve that is both central and peripheral. The alternative seems to be to split nerve into a peripheral and a central class (since it is not reasonable to model the optic nerve as a white matter tract).

Thoughts @cmungall @memartone?

**Comment by cmungall** [comment]
what we ended up doing but not documented in this ticket was a compromise: CN retains a nerve classification, but we introduce a new grouping [UBERON:0034713](http://purl.obolibrary.org/obo/UBERON_0034713) ! cranial neuron projection bundle

here is a subset:

![image](https://user-images.githubusercontent.com/50745/30245616-d5bb2b62-9594-11e7-8135-df54224a3b86.png)

it's not ideal. The weirdly named grouping is more inclusive than you might want as it contains other projection bundles beyond the classic ones. But everything is consistent at least.

I'm open to your suggestion. If implemented how would you feel about

 1. The existing [UBERON:0001785](http://purl.obolibrary.org/obo/UBERON_0001785) ! cranial nerve gets renamed to something like "true cranial nerve" or "cranial PNS nerve" (since this it's semantics)
 2. We introduce a new ID for "cranial nerve" which is treated as you as nothing more than a colloquial grouping with asserted subclasses.

**Comment by cmungall** [comment]
@tgbugs how do you feel about the suggestion above?

**Comment by tgbugs** [comment]
That suggestion makes sense to me and I think is reasonable going forward.

Relatedly, we are doing some deeper modelling of nerves (or really nerve sheaths and neuron populations) at the moment, and I have a number of thoughts, but not at a point where it makes sense to try to integrate because we are still iterating.

**Comment by cmungall** [comment]
Following up more here. Right now there are terms "X nerve fiber bundle" that correspond to the cranial nerves (and pseudonerves) yet are underspecified and unconnected:

```yaml
[Term]
id: UBERON:0006090
name: glossopharyngeal nerve fiber bundle
synonym: "central part of glossopharyngeal nerve" EXACT [BIRNLEX:1274]
synonym: "central part of glossopharyngeal nerve" EXACT [FMA:72627]
synonym: "fibrae nervi glossopharyngei" RELATED LATIN [NeuroNames:793]
synonym: "glossopharyngeal nerve fiber bundle" EXACT [BIRNLEX:1274]
synonym: "glossopharyngeal nerve fibers" EXACT [BIRNLEX:1274]
synonym: "glossopharyngeal nerve fibers" EXACT [FMA:72627]
synonym: "glossopharyngeal nerve tract" EXACT [FMA:72627]
synonym: "ninth cranial nerve fibers" EXACT [BIRNLEX:1274]
synonym: "ninth cranial nerve fibers" EXACT [FMA:72627]
xref: BAMS:9nf
xref: BIRNLEX:1274
xref: FMA:72627
xref: http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=793 {source="BIRNLEX:1274"}
xref: UMLS:C0175550 {source="BIRNLEX:1274"}
is_a: UBERON:0000122 ! neuron projection bundle
relationship: part_of UBERON:0001896 ! medulla oblongata

[Term]
id: UBERON:0006116
name: vagal nerve fiber bundle
synonym: "central part of vagus nerve" EXACT [BIRNLEX:765]
synonym: "central part of vagus nerve" EXACT [FMA:72628]
synonym: "fibrae nervi vagi" RELATED LATIN [NeuroNames:794]
synonym: "tenth cranial nerve fibers" EXACT [BIRNLEX:765]
synonym: "tenth cranial nerve fibers" EXACT [FMA:72628]
synonym: "vagal nerve fiber bundle" EXACT [BIRNLEX:765]
synonym: "vagal nerve fibers" EXACT [BIRNLEX:765]
synonym: "vagal nerve fibers" EXACT [FMA:72628]
synonym: "vagal nerve tract" EXACT [FMA:72628]
xref: BAMS:10nf
xref: BIRNLEX:765
xref: FMA:72628
xref: http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=794 {source="BIRNLEX:765"}
xref: UMLS:C0175551 {source="BIRNLEX:765"}
is_a: UBERON:0000122 ! neuron projection bundle
relationship: part_of UBERON:0001896 ! medulla oblongata

[Term]
id: UBERON:0006117
name: accessory nerve fiber bundle
def: "Fibers of the accessory nerve (11th cranial nerve) contained within the medulla." [BIRNLEX:916]
synonym: "accessory nerve fiber bundle" EXACT [BIRNLEX:916]
synonym: "accessory nerve fibers" EXACT [BIRNLEX:916]
synonym: "accessory nerve fibers" EXACT [FMA:72626]
synonym: "accessory nerve tract" EXACT [FMA:72626]
synonym: "eleventh cranial nerve fibers" EXACT [FMA:72626]
synonym: "fibrae nervi accessorius" RELATED LATIN [NeuroNames:792]
xref: BAMS:11nf
xref: BIRNLEX:916
xref: FMA:72626
xref: http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=792 {source="BIRNLEX:916"}
xref: UMLS:C0175549 {source="BIRNLEX:916"}
is_a: UBERON:0000122 ! neuron projection bundle
relationship: part_of UBERON:0001896 ! medulla oblongata
```
