### ISSUE TITLE
Create an antipattern for Uberon set-of-X terms

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3273]
We have some obsoleted terms:

```yaml
id: UBERON:0004551
name: obsolete set of proper plantar digital arteries
synonym: "arteriae digitales plantares propriae" EXACT LATIN [FMA:71564, FMA:TA]
synonym: "plantar digital arteries proper" EXACT [FMA:71564]
synonym: "plantar digital arteries proper set" EXACT [FMA:71564]
property_value: curator_notes "this class was made obsolete, as uberon does not include 'Set of X' classes. For now, the FMA class for set of plantar digital arteries proper is under UBERON:0004540, but it is unclear if this is correct" xsd:string
is_obsolete: true
consider: FMA:71564
```

It would be good to be absolutely crystal clear that set-of-X is an antipattern in Uberon. My way of doing this would be to have a yaml in the dp folder that is marked as antipattern.

We have some that apparently fall into this DP

```yaml
[Term]
id: UBERON:0009679
name: set of lower jaw teeth
def: "A tooth row that is part of a skeleton of lower jaw." [OBOL:automatic]
subset: pheno_slim
synonym: "arcus dentalis inferior" EXACT LATIN [FMA:TA]
synonym: "lower dental arcade" EXACT [FMA:55635]
synonym: "lower jaw teeth" EXACT [EHDAA2:0001029]
synonym: "mandibular dental arcade" RELATED [FMA:55635]
synonym: "set of all lower teeth" EXACT [FMA:55635]
xref: EHDAA2:0001029
xref: FMA:55635
intersection_of: UBERON:0009678 ! tooth row
intersection_of: part_of UBERON:0003278 ! skeleton of lower jaw

[Term]
id: UBERON:0009680
name: set of upper jaw teeth
def: "A tooth row that is part of a skeleton of upper jaw." [OBOL:automatic]
subset: pheno_slim
synonym: "arcus dentalis superior" EXACT LATIN [FMA:TA]
synonym: "maxillary dental arcade" RELATED [FMA:55634]
synonym: "set of all upper teeth" EXACT [FMA:55634]
synonym: "upper dental arcade" EXACT [FMA:55634]
synonym: "upper jaw teeth" EXACT [EHDAA2:0002129]
xref: EHDAA2:0002129
xref: FMA:55634
intersection_of: UBERON:0009678 ! tooth row
intersection_of: part_of UBERON:0003277 ! skeleton of upper jaw
```

I'd argue this is just a naming issue. "dental arcade" might be better.

I would also make it clear that mereological sums of members all of the same type are OK in Uberon, but I think we should limit this and have highly circumscribed DPs, e.g.

- musculature
- vasculature
- dentition
- hair
- pairs (of lungs, of buttocks)
- any more?

Even these allowed ones are potentially confusing to curators (e.g. for gene expression annotation they are equivalent to their members)

We also have an fma_set_term property:

```yaml
id: UBERON:0012247
name: cervical gland
def: "Mucus-secreting glands in the mucosa of the uterine cervix." [http://www.thefreedictionary.com/cervical+glands]
synonym: "glandulae cervicales" EXACT [FMA:TA]
xref: NCIT:C32296
xref: SCTID:280836000
xref: UMLS:C2724437 {source="ncithesaurus:Cervical_Gland"}
is_a: UBERON:0000414 ! mucous gland
intersection_of: UBERON:0002365 ! exocrine gland
intersection_of: part_of UBERON:0000002 ! uterine cervix
relationship: fma_set_term FMA:71646
relationship: part_of UBERON:0012248 ! cervical mucosa
```

It's not clear this brings a lot of value. It may be useful to axiomatize-by-proxy the FMA set terms (they are poorly linked in FMA) but I think the value is highly minimal here as I would simply recommend the FMA set terms are ignored. I don't know if we can get any documentation as to why they were added in the first place

it gets kind of mental here with 2nd order collections:

```yaml
id: UBERON:0014381
name: whorl of hair
def: "A patch of hair growing in the opposite direction of the rest of the hair." [Wikipedia:Hair_whorl]
comment: Hair whorls occur in most hairy animals, on the body as well as on the head. Hair whorls, also known as crowns, swirls, trichoglyphs, or cowlicks, can be either clockwise or counterclockwise in direction of growth.[WP]
subset: pheno_slim
synonym: "hair whorl" BROAD []
synonym: "whorl" BROAD []
xref: Wikipedia:Hair_whorl
is_a: UBERON:0010164 ! collection of hairs
relationship: fma_set_term FMA:76564 ! Set of hair whorls
```

here is one where there is a valid reason for making a bona-fide pair of buttocks in Uberon 🍑 :

```yaml
id: UBERON:0013691
name: buttock
def: "A zone of soft tissue located on the posterior of the lateral side of the pelvic region corresponding to the gluteal muscles." [http://orcid.org/0000-0002-6601-2165, Wikipedia:Buttocks]
subset: efo_slim
subset: pheno_slim
synonym: "buttocks" RELATED PLURAL [Wikipedia:Buttocks]
synonym: "clunis" EXACT [FMA:25245]
synonym: "gluteal part of pelvic girdle" EXACT [FMA:25245]
synonym: "gluteal region" EXACT [FMA:25245]
synonym: "regio glutealis" EXACT LATIN [FMA:TA]
xref: CALOHA:TS-2224
xref: EFO:0003070
xref: FMA:25245
xref: MESH:D002081
xref: NCIT:C89806
xref: SCTID:362677002
xref: UMLS:C0006497 {source="ncithesaurus:Buttock"}
xref: Wikipedia:Buttocks
is_a: UBERON:0034929 ! external soft tissue zone
relationship: fma_set_term FMA:76446
relationship: has_part UBERON:0002000 ! gluteal muscle
relationship: in_lateral_side_of UBERON:0001271 ! pelvic girdle region
relationship: part_of UBERON:0001271 {source="FMA"} ! pelvic girdle region
property_value: has_relational_adjective "gluteal" xsd:string
```
