### ISSUE TITLE
Consistently populate liver sectors and segments

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3322]
In general, when we adopt a classification schema - such as the classic Couinaud subdivision of the liver - we want to adopt it *in whole* and make efforts for reasonable completeness

We have two "sector" terms populated:

```yaml
id: UBERON:8600015
name: posterior sector of right lobe of liver
def: "The posterior sector of the right lobe of the liver." [PMID:30992874]
synonym: "lateral sector of right lobe of liver" EXACT [PMID:24453062]
synonym: "liver right lateral lobe" RELATED [https://orcid.org/0000-0002-6443-9376]
synonym: "right hepatic posterior sector" EXACT [PMID:30487943]
is_a: UBERON:0001062 ! anatomical entity
relationship: part_of UBERON:0001114 ! right lobe of liver
```

```yaml
id: UBERON:8600016
name: anterior sector of right lobe of liver
def: "The anterior sector of the right lobe of the liver." [PMID:30992874]
synonym: "liver right medial lobe" RELATED [https://orcid.org/0000-0002-6443-9376]
synonym: "medial sector of right lobe of liver" EXACT [PMID:24453062]
synonym: "right hepatic anterior sector" EXACT [PMID:30487943]
is_a: UBERON:0001062 ! anatomical entity
relationship: part_of UBERON:0001114 ! right lobe of liver
```

This is based on two pubs:

 - https://pubmed.ncbi.nlm.nih.gov/24453062 Clinical and surgical anatomy of the liver: a review for clinicians
     - classic Couinaud system with important changes by the 2000 Brisbane committee
     - the liver is divided into the hemilivers, sectors, and segments in order of descending magnitude
 - https://pubmed.ncbi.nlm.nih.gov/30992874 Normal liver anatomy
    - this has a nice depiction of the hemiliver/sector/segment breakdown

![img](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6448666/bin/CLD-2-S1-g006.jpg)

The wikipedia page on segments is also useful

https://en.wikipedia.org/wiki/Liver_segment

![img](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Liver_04_Couinaud_classification.svg/720px-Liver_04_Couinaud_classification.svg.png)

My rendering as a partonomy (lobe -> section/sector -> segment)

* liver
    - right lobe
       - right anterior section
            - segment V
            -  segment VIII
        - right posterior section
             - segment VI
             - segment VII
    - left lobe
        - left medial section
            - segment I (aka caudate *lobe*)
            - segment IV
                  - IVb == quadrate *lobe*
        - left lateral section
             - segment II
             - segment III

Ideally we would have terms in uberon for lobes, segments, and sectors, and we would populate these consistently. It is a bit challenging to do this though, because in Couinaud the caudate *lobe* is actually a *segment* (Segment I). Ideally we would avoid dual asserted classification over this.

We also may want to make these kinds of atlas-level subdivisions species-specific

This is the FMA classification

* [] FMA:62955 ! Anatomical entity
    * [i] FMA:61775 ! Physical anatomical entity
        * [i] FMA:67165 ! Material anatomical entity
            * [i] FMA:305751 ! Anatomical structure
                * [i] FMA:67135 ! Postnatal anatomical structure
                    * [i] FMA:82472 ! Cardinal organ part
                        * [i] FMA:14065 ! Organ component
                            * [i] FMA:82478 ! Lobular organ component
                                * [i] FMA:82494 ! Lobular segment
                                    * [i] **FMA:14495 ! Lobular segment of liver**
                                        * [i] FMA:72263 ! Segment of left lobe of liver
                                            * [i] FMA:14501 ! Lateral segment of left lobe of liver
                                            * [i] FMA:14500 ! Medial segment of left lobe of liver
                                        * [i] FMA:15740 ! Hepatovenous sector
                                            * [i] FMA:15751 ! Posterior sector of left liver
                                            * [i] FMA:15750 ! Anterior sector of left liver
                                            * [i] FMA:15749 ! Posterior sector of right liver
                                            * [i] FMA:15748 ! Anterior sector of right liver
                                            * [i] FMA:15732 ! Dorsal sector of liver
                                        * [i] FMA:14496 ! Segment of right lobe of liver
                                            * [i] FMA:236862 ! Superior segment of right lobe of liver
                                            * [i] FMA:236860 ! Inferior segment of right lobe of liver
                                            * [i] FMA:14499 ! Posterior segment of right lobe of liver
                                            * [i] FMA:14498 ! Anterior segment of right lobe of liver

This seems largely consistent with Couinaud.

I would recommend adding general groupings for liver sector/section and segment, making it explicit we are following the Couinaud scheme, add mappings to FMA
