### ISSUE TITLE
NTR: exocrine gland duct

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3323]
We should consistently adopt a simple subdivision: exocrine gland = acinus + duct

![img](https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Centroacinar_cells.jpg/500px-Centroacinar_cells.jpg)

We have a very general morpho-functional grouping class for "duct"

```yaml
id: UBERON:0000058
name: duct
def: "A tubular structure that transports secreted or excreted substances." [http://orcid.org/0000-0002-6601-2165, http://www.siumed.edu/~dking2/intro/glands.htm#ducts]
subset: grouping_class
synonym: "anatomical duct" EXACT []
synonym: "ducts" RELATED OMO:0003004 [XAO:0004000]
synonym: "exocrine duct" NARROW []
synonym: "exocrine gland duct" NARROW []
xref: AAO:0011123
xref: FMA:30320
xref: galen:Duct
xref: NCIT:C12948
xref: SCTID:91726008
xref: TAO:0005171
xref: UMLS:C0687028 {source="ncithesaurus:Duct"}
xref: Wikipedia:Duct_(anatomy)
xref: XAO:0004000
xref: ZFA:0005171
is_a: UBERON:0000063 ! organ subunit
relationship: conduit_for UBERON:0000463 ! organism substance
relationship: has_part UBERON:0013686 ! anatomical conduit space
relationship: has_part UBERON:0034969 ! epithelial layer of duct
relationship: has_quality PATO:0002299 ! tubular
property_value: external_definition "A tube shaped portion of tissue lined with epithelial cells that collects secretions and routes them to their destination[ZFA:0005171]." xsd:string {source="ZFA:0005171"}
property_value: external_ontology_notes "Most ducts, but not all, are exocrine gland ducts. Some ontologies classify structures such as the oviduct here." xsd:string
```

We also have a strange grouping:

```yaml
id: UBERON:0003928
name: digestive system duct
def: "A duct that is part of a digestive system [Automatically generated definition]." [OBOL:automatic]
synonym: "duct of digestive system" EXACT [OBOL:automatic]
synonym: "duct of gastrointestinal system" EXACT [OBOL:automatic]
synonym: "gastrointestinal system duct" EXACT [OBOL:automatic]
xref: TAO:0005162
xref: ZFA:0005162
intersection_of: UBERON:0000058 ! duct
intersection_of: part_of UBERON:0001007 ! digestive system
```

I think this is based on a misreading of the attempt of the ZFA term, which doesn't actually include any exocrine gland ducts

* [] ZFA:0005171 ! duct
    * [i] **ZFA:0005162 ! digestive system duct**
        * [i] ZFA:0005748 ! intrapancreatic duct
            * [i] ZFA:0005752 ! main intrapancreatic duct
            * [i] ZFA:0005751 ! pancreatic interlobular duct
            * [i] ZFA:0005750 ! pancreatic intralobular duct
            * [i] ZFA:0005749 ! intercalated duct pancreas
        * [i] ZFA:0005346 ! extrapancreatic duct
        * [i] ZFA:0005170 ! extrahepatic duct
        * [i] ZFA:0005169 ! intrahepatic bile duct
            * [p] ZFA:0009379 ! intrahepatic bile duct epithelial cell
        * [i] ZFA:0005167 ! hepatopancreatic ampulla
        * [i] ZFA:0005166 ! cystic duct
        * [i] ZFA:0005165 ! common bile duct
        * [i] ZFA:0005164 ! bile ductule
        * [i] ZFA:0001372 ! pancreatic duct
            * [p] ZFA:0009380 ! pancreatic ductal cell
            * [p] ZFA:0005748 ! intrapancreatic duct
                * [i] ZFA:0005752 ! main intrapancreatic duct
                * [i] ZFA:0005751 ! pancreatic interlobular duct
                * [i] ZFA:0005750 ! pancreatic intralobular duct
                * [i] ZFA:0005749 ! intercalated duct pancreas
            * [p] ZFA:0005346 ! extrapancreatic duct
        * [i] ZFA:0001100 ! hepatic duct
            * [p] ZFA:0005170 ! extrahepatic duct
            * [p] ZFA:0005165 ! common bile duct

Immediate recommendation:

1. create a new term for exocrine gland duct
2. define as duct and part-of some exocrine gland

I also recommend

3. using this new term as the genus for all exocrine gland ducts
4. Adding a DP constraint such that all EGs must have duct and acinus portions
