### ISSUE TITLE
skin of umbilical area should be part of periumbilical region

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3324]
We have

```yaml
id: UBERON:8480053
name: skin of umbilical area
def: "A zone of skin that is part of the umbilicus and the periumbilical region." [https://orcid.org/0000-0002-0819-0473]
is_a: UBERON:0000014 ! zone of skin
relationship: part_of UBERON:0000916 ! abdomen
```

Should be mapped to:

FMA:0327064 ! Skin of periumbilical region

but there is no relationship to umbilicus, the MRCA(p) is abdomen:

<img width="425" alt="image" src="https://github.com/user-attachments/assets/3f4de380-e226-437c-bf39-7fbb25db69bc">

I recommend adding 

umbilical area = umbilicus + perimumbilical region

and making an LD for skin of umbilical area
