### ISSUE TITLE
how should the relationship between a lymph node and the tissues they drain be represented?

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3325]
Related to

- #3221               

we have:

```yaml
id: UBERON:8480056
name: left supraclavicular lymph node
def: "Supraclavicular lymph node located on the left side of a entire appendicular skeleton. The left supraclavicular lymph node drains the kidney, cervix, testis, and pancreas into the thoracic duct." [PMID:31335020]
is_a: UBERON:0035279 ! supraclavicular lymph node

[Term]
id: UBERON:8480057
name: right supraclavicular lymph node
def: "Supraclavicular lymph node located on the right side of a entire appendicular skeleton. The right supraclavicular lymph node drains the breast, lung and upper esophagus into the right lymphatic duct." [PMID:31335020]
is_a: UBERON:0035279 ! supraclavicular lymph node
```

aside: these need logical defs following the laterality patterns

The textual gloss is biologically correct, but the drains relations we decided on connect a *vessel* to the drained tissue/organ. 

See

- https://github.com/oborel/obo-relations/issues/699

So following this schema we might have something like

`left supraclavicular lymph node CONTINUOUS_WITH left supraclavicular lymphatic vessel [new term] VESSEL_DRAINS_LYMPH_FROM [new relation] lung etc`

We would need a new relation here, as it's not blood that is drained, and it doesn't make sense to use the generic drains for lymph and the specific ones for blood
