### ISSUE TITLE
NTR: ileocecal fold

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3326]
https://en.wikipedia.org/wiki/Ileocecal_fold

see also:

```yaml
id: FMA:16532
name: Ileocecal fold
relationship: <http://purl.org/sig/ont/fma/lymphatic_drainage> FMA:235246 ! Anterior ileocolic lymphatic chain
relationship: <http://purl.org/sig/ont/fma/regional_part_of> FMA:19803 ! Posterior wall of greater sac
relationship: <http://purl.org/sig/ont/fma/regional_part_of> FMA:21194 ! Peritoneum of posterior wall of greater sac
is_a: FMA:20620 ! Peritoneal fold of cecum
```
