### ISSUE TITLE
Generalize all selected insect-X terms to arthropod

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3376]
All UBERON:6X terms were pseudogeneralized from a subset of FBbt deemed generally useful (primarily those reference in GO).

Many of these are in fact applicable to arthropods. At first I thought it might be easiest to first universally generalize these and then selectively restrict, but we have a bit of a mix, and it may be better to do this more carefully on an as needed basis.

I also think we should introduce a new TC annotation "applicable outside of", such that for any term labeled "arthropod X" we can say "exists some T where T is not insecta where this is applicable" and have the reasoner tell us if we have accidentally placed an arthropod term under an insect term.

But for now I think we just need to work through these selectively following the patterns below on an as-needed basis. These could later be yamlified. 

## Insect in label, logic says arthropod, term applies to arthropods

This is the most straightforward category:

```yaml
id: UBERON:6005096
name: insect stomatogastric nervous system
def: "A group of small, interconnected ganglia situated posterior to and between the two brain hemispheres and associated with the pharynx, esophagus and aorta." [FlyBase:FBrf0089570, PMID:12966498]
synonym: "stomodaeal nervous system" RELATED [FlyBase:FBrf0111704]
synonym: "stomodeal nervous system" RELATED [FlyBase:FBrf0111704]
is_a: UBERON:0011216 ! organ system subdivision
relationship: in_taxon NCBITaxon:6656 ! Arthropoda
relationship: part_of UBERON:0001017 ! central nervous system
```

The label says insect but neither the text def nor the logic restricts to insects. (and in fact the definition doesn't outright rule out non-arthropods). In this case we think generalizing to arthropods is a good idea.

I think it's safe to relabel this to arthropod.

## label says insect, logic is largely unrestricted, term should remain insect

```yaml
id: UBERON:6000006
name: insect head segment
def: "Any segment that is part of some insect head." [UBERON:cjm]
intersection_of: UBERON:0000914 ! organismal segment
intersection_of: part_of UBERON:0000033 ! head
relationship: never_in_taxon NCBITaxon:7742 ! Vertebrata <vertebrates>
```

It's not clear why this didn't get a TC. As it is, it's kind of odd.

when talking about head homology in arthropods we get into murky territory (let's not discuss in this issue). I think the most conservative thing to do is to add an insect TC, but we have to be careful we don't restrict any existentially dependent children (see proposal for new TC annotation above)

Action: add a TC to insect

## label says insect, logic indirectly restricts to insect

```yaml
id: UBERON:0005895
name: insect leg
def: "The walking appendages of each segment of the ventral adult external thorax[FBbt]. A leg derived from an imaginal disc[GO]." [FBbt:00004640, GO:0007480]
synonym: "imaginal disc-derived leg" EXACT [GO:0007480]
xref: MAT:0000095
xref: MIAA:0000095
xref: TGMA:0000164
is_a: UBERON:0000026 ! appendage
relationship: develops_from UBERON:0000939 ! imaginal disc
```

No action is strictly required here (other than to fix the ugly bipartite definition). Imaginal discs are already correctly restricted to insects. But we may still want to add a TC just to have a consistent pattern.

## label says insect, logic says insect, broad applicability is difficult

```
id: UBERON:6000020
name: insect abdomen
def: "The most posterior of the three tagma (UBERON:6000002)." [FlyBase:FBrf0166419]
is_a: UBERON:6000002 ! arthropod tagma
relationship: in_taxon NCBITaxon:50557 ! Insecta
```

There may be good reasons to generalize if abdomens are homologous, but this is signing us up for work that is not strictly necessary now. The exception is if there are existentially dependent children we want to generalize (eg some clearly homologous structure that is part of the abdomen in both)
