### ISSUE TITLE
Definition of common hepatic artery is truncated

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#3509]
```yaml
id: UBERON:0005436
name: common hepatic artery
def: "In anatomy, the common hepatic artery is a short blood vessel that supplies oxygenated blood to the liver, pylorus (a part of the stomach), duodenum (a part of the small intestine) and pancreas. It arises from the celiac artery and has the following branches:." [Wikipedia:Common_hepatic_artery]
```

Just shorten this further so it's not trailing
