### ISSUE TITLE
What are GAID references?

### ISSUE THREAD

**Issue by cthoyt** [obophenotype/uberon#3527]
As a specific part of #2205, can someone help me understand what GAID references are?

Here's a listing of usages across ontologies indexed in the Bioregistry: https://biopragmatics.github.io/oquat/unknowns/prefix/gaid

e.g., [`UBERON_0001508` (arch of the aorta)](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001508) references GAID:471

**Comment by dosumis** [comment]
Couldn't find via LLM.  Assigning Chris & Melissa as they may know from back in the day.

**Comment by cthoyt** [comment]
I would still like to know the answer

**Comment by cmungall** [comment]
https://github.com/obophenotype/uberon/issues/1373#issuecomment-335191942

**Comment by cmungall** [comment]
Gemina:
https://pmc.ncbi.nlm.nih.gov/articles/PMC2808878/

obo file is still here:
https://sourceforge.net/projects/gemina/

For prefix archaeologists, the prefixes in this file are like this:

```yaml
[Term]
id: TIGR.AOID:571
name: brain
def: "The part of the central nervous system contained within the cranium, comprising the prosencephalon, mesencephalon, and rhombencephalon. It is derived from the anterior part of the embryonic neural tube." [MESH:A.08.186.211]
related_synonym: "encephalon" []
xref_analog: MESH:A.08.186.211
is_a: TIGR.AOID:570 ! central nervous system
```

at some point these became:

```yaml
id: UBERON:0000955
name: brain
...
xref: GAID:571
```

I'm not sure why, perhaps there was a different iteration of the obo files

If you want to lean into the archaeology, the obo file also has:

 TIGR.AOID
 TIGR.DOID
 TIGR.GeOID
 TIGR.NIAID.CATID
 TIGR.ROID
 TIGR.SyOID
 TIGR.TMOID

All that remains of TIGR in bioregistry is the venerable https://bioregistry.io/registry/tigrfam
