### ISSUE TITLE
UBERON:0003199 egg chamber

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#476]
[Term]
id: UBERON:0003199
name: egg chamber
comment: Candidate for obsoletion

no term is proposed to replace it, any idea?

Thank you,

Anne

**Comment by gouttegd** [comment]
WARNING: This issue has been automatically closed because it has not been updated in more than 3 years. Please re-open it if you still need this to be addressed addressed addressed – we are now getting some resources to deal with such issues.

**Comment by cmungall** [comment]
```yaml
id: UBERON:0003199
name: egg chamber
comment: Candidate for obsoletion
synonym: "follicle" RELATED [FBbt:00004894]
synonym: "germarium derived egg chamber" EXACT [FBbt:00004894]
xref: HAO:0000287
xref: NCIT:C61362
xref: UMLS:C1571705 {source="ncithesaurus:Follicle"}
is_a: UBERON:0000464 ! anatomical space
property_value: seeAlso https://github.com/obophenotype/uberon/issues/476 xsd:anyURI
```

this is almost useless, no axioms other than anatomic space

see also https://github.com/obophenotype/uberon/issues/1524
